### ISSUE TITLE
advanced search keywords

### ISSUE THREAD

**Issue by jibe-b** [jibe-b/searx#1]
See beginning of discussion: https://github.com/asciimoo/searx/pull/522#discussion_r56772930

about: [base.py](https://github.com/jibe-b/searx/blob/advanced-search/searx/engines/base.py)

The BASE web interface enables advanced search with keywords:
- title:       "tit"
- author:  "aut"
- subject: "subj"
- url:         "url"
- date frame: "[yyyy TO yyyy]"
- ...

while the API uses 
- "dctitle"
- "dccreator"
- "dcsubject"
- "url"
- "dcdate" (no time frame)
- ...

and the web interface keywords are not implemented.

Replacing the occurence of the regular expression "tit:" by "dctitle=" in the query to match the API keywords would enable advanced inline search.

@pietsch Are the advanced search keywords implemented in a specific way that would be interesting to reproduce in the Searx engine? I have to admit I prefer keywords such as "author", "title" rather than "aut", "tit", in particular as Searx is intended for a  wider range of users, though it has the drawback of adding yet other keywords. Your opinion is highly welcome :)

**Comment by pietsch** [comment]
I do not fully understand what you are asking, but perhaps it helps to clarify some things:
- Using the BASE HTTP API, it should be possible to implement all the advanced search functions you see in the Web interface.
- Parameter names in the BASE APIs are inspired by the data format (OAI-DC, see [Dublin Core](https://en.wikipedia.org/wiki/Dublin_Core)) BASE is harvesting. These field names are not very intuitive beyond a very small technical community of repository administrators, so I would encourage you to use more natural terms when designing a user interface for Searx.

Does this answer your question?

**Comment by kvch** [comment]
Good point. Then I guess we could use author, title, etc. It might be more user-friendly. :)

**Comment by jibe-b** [comment]
> - Using the BASE HTTP API, it should be possible to implement all the advanced search functions you see in the Web interface.

True, it already works with regex replacement "author:" -> "dccreator".

> These field names are not very intuitive beyond a very small technical community of repository administrators, so I would encourage you to use more natural terms

@pietsch You touched the point that @kvch raised.

I consider enabling both "aut" and "author" keywords so that both techs and normal users can use them.

**Comment by kvch** [comment]
@jibe-b I would say that only one keyword should be enabled. Otherwise it would be a bit complicated. Strive to write simple code. ;)

Now you convinced me about using the more natural author keyword. I think for now that is enogh. If someone does not like it, it can be changed easily. :)

I think this question is being overcomplicated. We should move on, and focus on making your pull request mergeable. :)

**Comment by jibe-b** [comment]
I agree with you @kvch! So at this stage, the BASE engine works on my machine and passes travis, with the minimum of advanced search. I will continue on advanced search in this fork - there can still be some work done to enable "from yyyy to yyyy" and author:"Albert **Einstein"... (but not for this pull request)

But now, let's go back to https://github.com/asciimoo/searx/pull/522.
